config/routes.rb
Rails.application.routes.draw do

  
	devise_for :users
	devise_for :admins
	root to: "posts#index"
	
	resources :posts do 
		resource :map
		resources :charges
	end

	resources :tags
	resources :orders

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  def number
  	date_section = created_at.strftime('%y%m%d')
  	number_section = "%04d" % id

  	date_section + number_section
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, 
		styles: { thumb: '300x300>' },
		storage: :s3, 
		s3_credentials: {
			bucket: 'PinstaGram2',
			access_key_id: Rails.application.secrets.s3_access_key,
			secret_access_key: Rails.application.secrets.s3_secret_key
		}
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  	belongs_to :user
  	has_and_belongs_to_many :tags 

  	def tag_names
  		''
  	end

  	def tag_names=(tag_list)
  		return nil if tag_list == ''
  		tag_list.split(/,\s?/).uniq.each do |tag_name|
  			formatted_name = '#'+tag_name.delete('#')
  			tag = Tag.find_or_create_by(name: formatted_name)
  			tags << tag
  		end
  	end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	validates :name, uniqueness: true
	has_and_belongs_to_many :posts

	def to_param
		name.delete '#'
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
		@post = Post.find params[:post_id]
	end

	def create
		@post = Post.find params[:post_id]
		@amount = 100 * @post.amount

		customer = Stripe::Customer.create(
		:email => 'example@stripe.com',
		:card  => params[:stripeToken]
		)

		charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount.to_i,
	    :description => "Print of #{@post.title}",
	    :currency    => 'usd'
	  	)

	  	Order.create(user: current_user, post: @post)
	  	flash[:notice] = 'Thanks for your order'
	  	redirect_to '/posts'

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to post_charges_path(@post)
	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def show
		@post = Post.find params[:post_id]
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	
	def index
  		authenticate_admin!
  		@orders = Order.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post].permit(:title, :description, :image, :tag_names, :address, :amount))
		@post.user = current_user
		@post.save!

		redirect_to posts_path
	end

	def show
		@post = Post.find params[:id]
	end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by_name ('#'+ params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/new.html.erb
<div class='container'>
	<%= form_tag post_charges_path(@post) do %>
	  <article>
	    <label class="amount">
	      <span>Buy print for <%= number_to_currency(@post.amount) %></span>
	    </label>
	  </article>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.application.secrets.stripe_public_key %>"
	          data-description="A beautiful print"
	          data-amount="<%= 100 * @post.amount.to_i %>"></script>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Pinstagram2</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Pinstagram2</a>
        </div>
        <div class="navbar-collapse collapse">
        	<%= form_for(User.new, as: :user, url: session_path(:user), html: {class: 'navbar-form navbar-right'}) do |f| %>

			  	<div class="form-group"><%= f.email_field :email, placeholder: 'Email', class: 'form-control' %></div>

			  	<div class="form-group"><%= f.password_field :password, placeholder: 'Password', class: 'form-control' %></div>

				<%= f.button "Sign in", class: 'btn btn-primary' %>
			<% end %>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <div class="container">
    	<footer>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
        	<p>&copy; Painted Ltd. 2014</p>
    	</footer>
    </div> <!-- /container -->


  </body>
</html>

app/views/maps/show.html.erb
<div class='container'>
  <div id="map" data-id=<%= @post.id %>></div>
</div>

app/views/orders/index.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-4'>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Orders</h3>
				</div>
				<div class="panel-body">
				<% if @orders.any? %>
				  <% @orders.each do |order| %>
				    <p><%= order.user.email %></p>
				    <p><%= link_to order.post.title, '/posts' %></p>
				    <p><%= order.number %></p>
				  <% end %>
				<% else %>
				  No orders yet
				<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/_post.html.erb
<div class='col-md-4'>
	<div class="panel panel-default">
	  <div class="panel-heading">
	    <h3 class="panel-title"><%= post.title %></h3>
	  </div>
	  <div class="panel-body">
	    <% if post.image.present? %>
			<%= image_tag post.image.url(:thumb), class: 'uploaded-pic' %><br>
		<% end %>
		<p><%= post.description %></p>
		<p><% post.tags.each do |tag| %>
			<%= link_to tag.name, tag_path(tag) %></p>
		<% end %>
		<% unless post.address.blank? %>
			<p><%= link_to 'Map', post_map_path(post), class: 'btn btn-warning' %></p>
		<% end %>
		<p><%= number_to_currency(post.amount) %></p>
		<p><%= link_to "Buy", new_post_charge_path(post), class: 'btn btn-lg btn-default'%></p>
	  </div>
	  <div class="panel-footer">Posted by: <%= post.user.email %></div>
	</div>					
</div>

app/views/posts/index.html.erb
<% unless user_signed_in? %>
	<div class="jumbotron">
	  <div class="container">
	    <h1>Welcome to Painted's Mock Instagram</h1>
	    <p>This is a simple mock Instagram type site created by Will Allen from Painted Ltd. in London, UK.  If you are interested in work by Painted Ltd. please get in touch with us.</p>
	    <p>
	    	<%= link_to 'Sign Up »', new_user_registration_path, class: "btn btn-primary btn-lg" %>
	    </p>
	  </div>
	</div>
<% end %>
<div class='container'>
	<% if @posts.any? %>
		<% @posts.in_groups_of(3, false).each do |post_triplet| %>
			<div class='row'>
				<%= render post_triplet %>
			</div>
		<% end %>
	<% else %>
		<h1>No posts yet</h1>
	<% end %>
<%= link_to 'New post', new_post_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/posts/new.html.erb
<div class='container'>
	<div class='row'>
		<div class='col-md-4'>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">New Post</h3>
				</div>
				<div class="panel-body">
					<%= form_for @post, html: { multipart: true } do |f| %>
						<p><%= f.label :title %><br>
						<%= f.text_field :title %></p>

						<p><%= f.label :address %><br>
						<%= f.text_field :address %></p>

						<p><%= f.label :description %><br>
						<%= f.text_area :description %></p>

						<p><%= f.label :amount %><br>
						<%= f.text_field :amount %></p>

						<p><%= f.label :image %><br>
						<%= f.file_field :image %></p>

						<p><%= f.label :tag_names, 'Tags' %><br>
						<%= f.text_field :tag_names, data: {role: 'tagsinput'} %></p>



						<%= f.submit 'Post it!', class: "btn btn-primary btn-lg" %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/tags/show.html.erb
<h1>Posts associated with <%= @tag.name %></h1>

<div class='row'>
	<%= render @tag.posts %>
</div>